name: Build and release project
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Project preparation
        run: npm install -g pnpm
      - name: Install ImageMagick (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install imagemagick
      - name: Install ImageMagick (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://imagemagick.org/archive/binaries/magick
          chmod +x magick
      - name: Install dependencies
        run: pnpm install
      - name: Build, package and publish release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
